#!/usr/bin/env bash
# installing nginx on web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw "Nginx HTTP"

echo "Hello World!" | sudo tee /var/www/html/index.html

# testing nginx config
sudo nginx -t

sudo service nginx reload
