#!/bin/bash

# Check if the script is run as root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Create a new Nginx configuration file for the custom 404 page
sudo tee /etc/nginx/sites-available/custom_404 <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}
EOF

# Enable the new configuration by linking it to the sites-enabled directory
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Test Nginx configuration for any syntax errors
sudo nginx -t

# If the configuration test is successful, reload Nginx to apply the changes
sudo service nginx restart
