#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  franca_frontend
        bind *:80
        mode http
        default_backend franca_backend
backend franca_backend
        balance roundrobin
        server 399487-web-01 3.90.83.41:80 check
        server 399487-web-02 100.25.12.72:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
